# Generated by Django 3.2.8 on 2021-11-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=50, unique=True)),
                ('persian_name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=50, unique=True)),
                ('cv', models.CharField(max_length=1000, unique=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('whatsappId', models.CharField(max_length=20, null=True)),
                ('instagramId', models.CharField(max_length=20, null=True)),
                ('phoneNumber', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
