# Generated by Django 3.2.8 on 2021-12-25 11:14

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='datetime',
            field=django_jalali.db.models.jDateTimeField(default=None, null=True),
        ),
    ]
