# Generated by Django 3.2.8 on 2021-11-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coach',
            name='cv',
            field=models.TextField(),
        ),
    ]
