# Generated by Django 3.2.8 on 2021-11-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20211128_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='instagramId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='whatsappId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
