# Generated by Django 3.2.8 on 2021-12-25 11:15

from django.db import migrations
import django_jalali.db.models
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_video_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order', '-datetime']},
        ),
        migrations.AlterField(
            model_name='video',
            name='datetime',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now, null=True),
        ),
    ]
