# Generated by Django 3.2.8 on 2021-11-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20211128_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
