# Generated by Django 3.2.8 on 2021-12-26 06:45

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20211225_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2021, 12, 26), null=True),
        ),
    ]
