# Generated by Django 3.2.8 on 2021-11-28 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_coach_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['order']},
        ),
    ]
