# Generated by Django 3.2.8 on 2022-12-31 12:04

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20211226_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=10)),
                ('date', django_jalali.db.models.jDateField(default=datetime.date(2022, 12, 31), null=True)),
                ('image_filename_1', models.CharField(blank=True, max_length=50, null=True)),
                ('image_caption_1', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_filename_2', models.CharField(blank=True, max_length=50, null=True)),
                ('image_caption_2', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_filename_3', models.CharField(blank=True, max_length=50, null=True)),
                ('image_caption_3', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['order', 'date'],
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
