# Generated by Django 3.2.8 on 2022-12-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20221231_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['order', 'date'], 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_caption_1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_caption_2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_caption_3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_filename_1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_filename_2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_filename_3',
        ),
    ]
