# Generated by Django 3.2.8 on 2021-12-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20211205_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='link_caption',
            field=models.CharField(default='more‥', max_length=1000),
        ),
    ]
