# Generated by Django 3.2.8 on 2021-12-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_course_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='current',
            new_name='active',
        ),
    ]
