# Generated by Django 3.2.8 on 2021-12-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20211206_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='semester',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='semester',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
