# Generated by Django 3.2.8 on 2021-12-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='image_filename',
            new_name='image_filename_2',
        ),
        migrations.AddField(
            model_name='content',
            name='image_filename_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
