# Generated by Django 3.2.8 on 2021-12-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20211208_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image_filename_1', models.CharField(blank=True, max_length=50, null=True)),
                ('image_caption_1', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_filename_2', models.CharField(blank=True, max_length=50, null=True)),
                ('image_caption_2', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_filename_3', models.CharField(blank=True, max_length=50, null=True)),
                ('image_caption_3', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_filename_4', models.CharField(blank=True, max_length=50, null=True)),
                ('image_caption_4', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_filename_5', models.CharField(blank=True, max_length=50, null=True)),
                ('image_caption_5', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
