# Generated by Django 3.2.8 on 2021-12-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20211208_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image_caption_5',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image_filename_5',
        ),
    ]
