# Generated by Django 3.2.8 on 2021-12-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20211209_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('image_filename_1', models.CharField(blank=True, max_length=50, null=True)),
                ('image_caption_1', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_filename_2', models.CharField(blank=True, max_length=50, null=True)),
                ('image_caption_2', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_filename_3', models.CharField(blank=True, max_length=50, null=True)),
                ('image_caption_3', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
