# Generated by Django 3.2.8 on 2021-12-10 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Newsvebose', 'verbose_name_plural': 'Newsssss'},
        ),
    ]
