# Generated by Django 3.2.8 on 2021-12-10 04:56

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='jalalidate',
            field=django_jalali.db.models.jDateField(default=datetime.date(2021, 12, 10), null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date(2021, 12, 10), null=True),
        ),
    ]
