# Generated by Django 3.2.8 on 2021-12-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20211210_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
    ]
