# Generated by Django 3.2.8 on 2021-12-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_news_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='jalalidate',
            new_name='date',
        ),
    ]
