# Generated by Django 3.2.8 on 2021-12-10 05:12

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.IntegerField(default=10)),
                ('date', django_jalali.db.models.jDateField(default=datetime.date(2021, 12, 10), null=True)),
            ],
            options={
                'ordering': ['order', 'date'],
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['order', 'date'], 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='order',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='order',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='order',
            field=models.IntegerField(default=10),
        ),
    ]
