# Generated by Django 3.2.8 on 2021-12-22 03:37

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20211219_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, max_length=1000, null=True)),
                ('icon', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.IntegerField(default=10)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2021, 12, 22), null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2021, 12, 22), null=True),
        ),
    ]
